### ISSUE TITLE
Null Reference when saving plugin config

### ISSUE THREAD

**Issue by NeoNC72** [Aida-Enna/TwitchXIV#3]
```
20:43:12.769 | ERR | Exception during raise of "Void Draw()"
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at TwitchXIV.PluginUI.Draw() in /work/repo/PluginUI.cs:line 45
	   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\\Utility\EventHandlerExtensions.cs:line 124
```

Happens after clicking save.

```C#
 if (WOLClient.Client.IsConnected) { WOLClient.Client.Disconnect(); }
```
i assume WOLClient is null here

**Comment by NeoNC72** [comment]
seems like it works now, thanks!
